### ISSUE TITLE
Intelligent clearing of the LocalStorage

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#83]
As we are sometimes facing some problems due to the old values in the LocalStorage a intelligent way of removing the items should be added.
**This should do following:**

- [x] Flush the LocalStorage at the startup of the application if the app is in the development mode.

_There is going to be a debug property introduced in the config. #75_
- [x] Save a current application's version to the LocalStorage.
- [x] Clear the LocalStorage if the user installs a new version of the application.

_Compare the version number from the config with the last saved one. #75_

**Comment by patrickmuessig** [comment]
ready4review and merge

**Comment by skaldo** [comment]
@themetalone could you please review this?

**Comment by themetalone** [comment]
Review Log: 
- Moved clearing from home.ts to pdp constructor
- Clearing is performed via the IStorage interface. This removes rework effort if we should ever change the storage implementation
- optimized the clearing method a bit (removed the elseif since it's body would eventually be executed in either case)

**Comment by themetalone** [comment]
Reviewed and ready to merge. Will do this after lunch
